version: '3.1'
services:
  petdiniz_rmtp:
    build: ./rmtp
    image: 'pedrohfreitas/petdiniz_rmtp:1.0'
    restart: unless-stopped
    ports:
      - '1935:1935'
      - '8081:80'
  petdiniz_front:
    build: ./front
    image: 'pedrohfreitas/petdiniz_front:1.0'
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8083:443'
