version: '3.1'
services:
  petsdiniz_rmtp:
    build: ./rmtp
    image: 'pedrohfreitas/petsdiniz_rmtp:1.0'
    restart: unless-stopped
    ports:
      - '1935:1935'
      - '8081:8000'
  petsdiniz_front:
    build: ./front
    image: 'pedrohfreitas/petsdiniz_front:1.0'
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8083:443'
